//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitig.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("469")]
        public int k_SplitterDistance {
            get {
                return ((int)(this["k_SplitterDistance"]));
            }
            set {
                this["k_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool k_AlphabetVisible {
            get {
                return ((bool)(this["k_AlphabetVisible"]));
            }
            set {
                this["k_AlphabetVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point k_Location {
            get {
                return ((global::System.Drawing.Point)(this["k_Location"]));
            }
            set {
                this["k_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("709, 573")]
        public global::System.Drawing.Size k_ClientSize {
            get {
                return ((global::System.Drawing.Size)(this["k_ClientSize"]));
            }
            set {
                this["k_ClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState k_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["k_WindowState"]));
            }
            set {
                this["k_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool k_AlifUser1Visible {
            get {
                return ((bool)(this["k_AlifUser1Visible"]));
            }
            set {
                this["k_AlifUser1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool k_AlifUser2Visible {
            get {
                return ((bool)(this["k_AlifUser2Visible"]));
            }
            set {
                this["k_AlifUser2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool k_AlifUser3Visisble {
            get {
                return ((bool)(this["k_AlifUser3Visisble"]));
            }
            set {
                this["k_AlifUser3Visisble"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, 24")]
        public global::System.Drawing.Point k_TlsMainLocation {
            get {
                return ((global::System.Drawing.Point)(this["k_TlsMainLocation"]));
            }
            set {
                this["k_TlsMainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 39")]
        public global::System.Drawing.Point k_AlphabetLocation {
            get {
                return ((global::System.Drawing.Point)(this["k_AlphabetLocation"]));
            }
            set {
                this["k_AlphabetLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 0")]
        public global::System.Drawing.Point k_TlsTextLocation {
            get {
                return ((global::System.Drawing.Point)(this["k_TlsTextLocation"]));
            }
            set {
                this["k_TlsTextLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("141, 44")]
        public global::System.Drawing.Point k_TlsParagraphLocation {
            get {
                return ((global::System.Drawing.Point)(this["k_TlsParagraphLocation"]));
            }
            set {
                this["k_TlsParagraphLocation"] = value;
            }
        }
    }
}
